print('SEJA BEM VINDO AO EX.4')
print('')
a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço?', a.isspace())
print('É um numerico?', a.isnumeric())
print('Só tem letras maiúsculas?', a.isupper())
print('Só tem letras minúsculas?', a.islower())
